// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pressure Gauge Test_00

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_back_imagee_png, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Screen2_Container1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Screen2_Container1);
    lv_obj_set_width(ui_Screen2_Container1, 234);
    lv_obj_set_height(ui_Screen2_Container1, 233);
    lv_obj_set_x(ui_Screen2_Container1, -1);
    lv_obj_set_y(ui_Screen2_Container1, -2);
    lv_obj_set_align(ui_Screen2_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen2_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2_Image26 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Screen2_Image26, &ui_img_561637215);
    lv_obj_set_width(ui_Screen2_Image26, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Screen2_Image26, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Screen2_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Screen2_Image26, 122);
    lv_obj_set_style_bg_img_src(ui_Screen2_Image26, &ui_img_back_imagee_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Screen2_Image2, &ui_img_pointer2_png);
    lv_obj_set_width(ui_Screen2_Image2, LV_SIZE_CONTENT);   /// 117
    lv_obj_set_height(ui_Screen2_Image2, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_Screen2_Image2, -53);
    lv_obj_set_y(ui_Screen2_Image2, 0);
    lv_obj_set_align(ui_Screen2_Image2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen2_Image2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_pivot(ui_Screen2_Image2, 110, 6);

    lv_obj_add_event_cb(ui_Screen2_Container1, ui_event_Screen2_Container1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
