// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pressure Gauge Test_00

#ifndef _PRESSURE_GAUGE_TEST_00_UI_H
#define _PRESSURE_GAUGE_TEST_00_UI_H

#ifdef __cplusplus
extern "C" {
#endif

// #include "<lvgl.h>"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_Screen1_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Panel1;
void ui_event_Screen1_Label1(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Label1;
extern lv_obj_t * ui_Screen1_Image1;
extern lv_obj_t * ui_Screen1_Panel2;
extern lv_obj_t * ui_Screen1_Panel3;
void ui_event_Screen1_Image17(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Image17;
void ui_event_Screen1_Image18(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Image18;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
void ui_event_Screen2_Image3(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Image3;
extern lv_obj_t * ui_Screen2_Image4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_back_imagee_png);    // assets/back_imagee.png
LV_IMG_DECLARE(ui_img_1761860606);    // assets/KCLOGOred-.png
LV_IMG_DECLARE(ui_img_115859818);    // assets/down_17089412(1).png
LV_IMG_DECLARE(ui_img_up_17089412_png);    // assets/up_17089412.png
LV_IMG_DECLARE(ui_img_scale2__prev_ui_png);    // assets/Scale2__prev_ui.png
LV_IMG_DECLARE(ui_img_pointer2_png);    // assets/Pointer2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
