// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pressure Gauge Test_00

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_back_imagee_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Screen1, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_shadow_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Screen1_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Panel1, 255);
    lv_obj_set_height(ui_Screen1_Panel1, 251);
    lv_obj_set_x(ui_Screen1_Panel1, 1);
    lv_obj_set_y(ui_Screen1_Panel1, -1);
    lv_obj_set_align(ui_Screen1_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1_Panel1, &ui_img_back_imagee_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label1, -1);
    lv_obj_set_y(ui_Screen1_Label1, -9);
    lv_obj_set_align(ui_Screen1_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label1, "AirRidePro");
    lv_obj_clear_flag(ui_Screen1_Label1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen1_Label1, lv_color_hex(0xFF4000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Screen1_Label1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Screen1_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen1_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Screen1_Label1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Screen1_Label1, lv_color_hex(0xF6F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Screen1_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Screen1_Image1, &ui_img_1761860606);
    lv_obj_set_width(ui_Screen1_Image1, LV_SIZE_CONTENT);   /// 261
    lv_obj_set_height(ui_Screen1_Image1, LV_SIZE_CONTENT);    /// 109
    lv_obj_set_x(ui_Screen1_Image1, -2);
    lv_obj_set_y(ui_Screen1_Image1, -59);
    lv_obj_set_align(ui_Screen1_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Screen1_Image1, 164);

    ui_Screen1_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Panel2, 57);
    lv_obj_set_height(ui_Screen1_Panel2, 55);
    lv_obj_set_x(ui_Screen1_Panel2, 44);
    lv_obj_set_y(ui_Screen1_Panel2, 57);
    lv_obj_set_align(ui_Screen1_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Screen1_Panel2, LV_STATE_PRESSED);       /// States
    lv_obj_clear_flag(ui_Screen1_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1_Panel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Screen1_Panel2, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Screen1_Panel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_Screen1_Panel2, lv_color_hex(0xF75252), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_main_stop(ui_Screen1_Panel2, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_stop(ui_Screen1_Panel2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_dir(ui_Screen1_Panel2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Screen1_Panel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Screen1_Panel2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Screen1_Panel2, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_side(ui_Screen1_Panel2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Screen1_Panel2, lv_color_hex(0xFF2E2E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Screen1_Panel2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Screen1_Panel2, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Screen1_Panel2, 8, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen1_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Panel3, 55);
    lv_obj_set_height(ui_Screen1_Panel3, 55);
    lv_obj_set_x(ui_Screen1_Panel3, -44);
    lv_obj_set_y(ui_Screen1_Panel3, 55);
    lv_obj_set_align(ui_Screen1_Panel3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Screen1_Panel3, LV_STATE_PRESSED);       /// States
    lv_obj_clear_flag(ui_Screen1_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1_Panel3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Screen1_Panel3, 500, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Screen1_Panel3, lv_color_hex(0xC5FFCB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_Screen1_Panel3, lv_color_hex(0x15FF00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_main_stop(ui_Screen1_Panel3, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_stop(ui_Screen1_Panel3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_dir(ui_Screen1_Panel3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Screen1_Panel3, lv_color_hex(0x40FF51), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Screen1_Panel3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Screen1_Panel3, lv_color_hex(0x91FF93), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Screen1_Panel3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Screen1_Panel3, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Screen1_Panel3, 8, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen1_Image17 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Screen1_Image17, &ui_img_115859818);
    lv_obj_set_width(ui_Screen1_Image17, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Screen1_Image17, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Screen1_Image17, 44);
    lv_obj_set_y(ui_Screen1_Image17, 57);
    lv_obj_set_align(ui_Screen1_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Screen1_Image17, 30);

    ui_Screen1_Image18 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Screen1_Image18, &ui_img_up_17089412_png);
    lv_obj_set_width(ui_Screen1_Image18, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Screen1_Image18, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Screen1_Image18, -44);
    lv_obj_set_y(ui_Screen1_Image18, 56);
    lv_obj_set_align(ui_Screen1_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Screen1_Image18, 30);

    lv_obj_add_event_cb(ui_Screen1_Panel1, ui_event_Screen1_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Label1, ui_event_Screen1_Label1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Image17, ui_event_Screen1_Image17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Image18, ui_event_Screen1_Image18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
