// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pressure Gauge Test_00

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_back_imagee_png, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Screen2_Image3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Screen2_Image3, &ui_img_scale2__prev_ui_png);
    lv_obj_set_width(ui_Screen2_Image3, LV_SIZE_CONTENT);   /// 500
    lv_obj_set_height(ui_Screen2_Image3, LV_SIZE_CONTENT);    /// 500
    lv_obj_set_x(ui_Screen2_Image3, 1);
    lv_obj_set_y(ui_Screen2_Image3, 1);
    lv_obj_set_align(ui_Screen2_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Screen2_Image3, 122);
    lv_obj_set_style_bg_img_src(ui_Screen2_Image3, &ui_img_back_imagee_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Image4 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Screen2_Image4, &ui_img_pointer2_png);
    lv_obj_set_width(ui_Screen2_Image4, LV_SIZE_CONTENT);   /// 117
    lv_obj_set_height(ui_Screen2_Image4, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_Screen2_Image4, -51);
    lv_obj_set_y(ui_Screen2_Image4, 1);
    lv_obj_set_align(ui_Screen2_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen2_Image3, ui_event_Screen2_Image3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
