// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: HARLEY GAUGE 2 TEST

#ifndef _HARLEY_GAUGE_2_TEST_UI_H
#define _HARLEY_GAUGE_2_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1_Image1;
extern lv_obj_t * ui_Screen1_Label1;
extern lv_obj_t * ui_Screen1_Button1;
extern lv_obj_t * ui_Screen1_Button2;
void ui_event_Screen1_Container1(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Container1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Screen2_Image1;
extern lv_obj_t * ui_Screen2_Image2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_kclogored_png);    // assets/KCLOGOred.png
LV_IMG_DECLARE(ui_img_button_up_png);    // assets/Button up.png
LV_IMG_DECLARE(ui_img_button_up_p_png);    // assets/Button up_p.png
LV_IMG_DECLARE(ui_img_button_down_png);    // assets/Button down.png
LV_IMG_DECLARE(ui_img_button_down_p_png);    // assets/Button down_p.png
LV_IMG_DECLARE(ui_img_scale2_png);    // assets/Scale2.png
LV_IMG_DECLARE(ui_img_pointer2_png);    // assets/Pointer2.png
LV_IMG_DECLARE(ui_img_button_green_60_png);    // assets/button_green_60.png
LV_IMG_DECLARE(ui_img_button_red_60_png);    // assets/button_red_60.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
