// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pressure Gauge Test_00

#ifndef _PRESSURE_GAUGE_TEST_00_UI_H
#define _PRESSURE_GAUGE_TEST_00_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1_Image1;
extern lv_obj_t * ui_Screen1_Label1;
extern lv_obj_t * ui_Screen1_Button1;
extern lv_obj_t * ui_Screen1_Button2;
void ui_event_Screen1_Container1(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Container1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Screen2_Image1;
void ui_event_Screen2_Image2(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Image2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_kclogored_png);    // assets/KCLOGOred.png
LV_IMG_DECLARE(ui_img_button_up_orange_in_logo_colour_png);    // assets/Button up orange in logo colour.png
LV_IMG_DECLARE(
    ui_img_button_up_action_orange_in_logo_colour_png);    // assets/Button up action orange in logo colour.png
LV_IMG_DECLARE(ui_img_button_down_orange_in_logo_colour_png);    // assets/Button down orange in logo colour.png
LV_IMG_DECLARE(
    ui_img_button_down_action_orange_in_logo_colour_png);    // assets/Button down action orange in logo colour.png
LV_IMG_DECLARE(ui_img_scale2_png);    // assets/Scale2.png
LV_IMG_DECLARE(ui_img_pointer2_png);    // assets/Pointer2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
