// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pressure Gauge Test_00

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t* ui_Screen1;
lv_obj_t* ui_Screen1_Image1;
lv_obj_t* ui_Screen1_Label1;
lv_obj_t* ui_Screen1_Button1;
lv_obj_t* ui_Screen1_Button2;
void ui_event_Screen1_Container1(lv_event_t* e);
lv_obj_t* ui_Screen1_Container1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t* e);
lv_obj_t* ui_Screen2;
lv_obj_t* ui_Screen2_Image1;
void ui_event_Screen2_Image2(lv_event_t* e);
lv_obj_t* ui_Screen2_Image2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t* ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////


// #define RELAY1_PIN 25  // Relay 1 GPIO
// #define RELAY2_PIN 26  // Relay 2 GPIO


bool relay1_state = false;
bool relay2_state = false;
bool relay_print = false;


///////////////////// FUNCTIONS ////////////////////


void relay1_toggle(lv_event_t* e) {
  if (relay1_state) {
      relay1_state = false;
    } else {
      relay1_state = true;
    }
    relay_print = true;
}

void ui_event_Screen1_Container1(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_get_act());
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen2_screen_init);
    if (relay1_state) {
      relay1_state = false;
    } else {
      relay1_state = true;
    }
    relay_print = true;
  }
}


void ui_event_Screen2(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
    lv_indev_wait_release(lv_indev_get_act());
    _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen1_screen_init);

  }
}

void ui_event_Screen2_Image2(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    get_value(e);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void) {
  lv_disp_t* dispp = lv_disp_get_default();
  lv_theme_t* theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                            false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_Screen1_screen_init();
  ui_Screen2_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_Screen1);
}
