// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pressure Gauge Test_00

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void get_value(lv_event_t * e);



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
